version: "3"
services:
  app:
    build: .
    ports:
      - "8545:8545"
      - "8546:8546"
      - "30303:30303"
    volumes:
      - "./volumes/log:/log"
      - "./volumes/credentials:/go/go-pal/datadir"
    command: ["make", "node"]
    devices:
      - "/dev/net/tun:/dev/net/tun"
    tty: true
    privileged: true